require("config")
require("utils")
require("plugins").setup()

--require("user.options")
--require("user.keymaps")
--require("user.utils")
--require("user.colorscheme")
--require("user.lsp")
--require("user.telescope")
--require("user.telescope-ui-select")
--require("user.telescope-tabs")
--require("user.nvim-ts-autotag")
--require("user.plugins")
