#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
	selected=$1
else
	selected=$(
		echo "$(
			ls -d ~/dotfiles
			find ~/repos -mindepth 1 -maxdepth 1 -type d
		)" | fzf
	)
fi

if [[ -z $selected ]]; then
	exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

# tmux is not running, let alone in this terminal
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
	tmux new-session -s "$selected_name" -c "$selected"
	exit 0
fi

# tmux is running but not in this terminal/client
if ! tmux has-session -t="$selected_name" 2>/dev/null; then
	# detach the session from any other client
	tmux new-session -ds "$selected_name" -c "$selected"
fi

tmux switch-client -t "$selected_name"
