import * as Icons from "./components/icons.jsx";

export const apps = {
  "1Password 7": Icons.OnePassword,
  "Affinity Designer": Icons.AffinityDesigner,
  "Affinity Photo": Icons.AffinityPhoto,
  "Affinity Publisher": Icons.AffinityPublisher,
  Airmail: Icons.Airmail,
  Alacritty: Icons.Terminal,
  Alfred: Icons.Alfred,
  "Android Messages": Icons.AndroidMessages,
  "Android Studio": Icons.AndroidStudio,
  "App Store": Icons.AppStore,
  Arc: Icons.Arc,
  Atom: Icons.Atom,
  Audacity: Icons.Audacity,
  Bear: Icons.Bear,
  Bitwarden: Icons.BitWarden,
  Blender: Icons.Blender,
  "Brave Browser": Icons.BraveBrowser,
  Calendar: Icons.Calendar,
  Calibre: Icons.Book,
  "Canary Mail": Icons.Mail,
  Caprine: Icons.Caprine,
  Chromium: Icons.GoogleChrome,
  "CleanMyMac X": Icons.Desktop,
  ClickUp: Icons.ClickUp,
  "Code - Insiders": Icons.Code,
  Code: Icons.Code,
  "Color Picker": Icons.ColorPicker,
  "DEVONthink 3": Icons.DEVONthink3,
  Default: Icons.Default,
  "Discord Canary": Icons.Discord,
  Discord: Icons.Discord,
  "Discord PTB": Icons.Discord,
  Drafts: Icons.Drafts,
  Dropbox: Icons.Dropbox,
  Element: Icons.Element,
  Emacs: Icons.Emacs,
  "Evernote Legacy": Icons.EvernoteLegacy,
  FaceTime: Icons.FaceTime,
  Fantastical: Icons.Calendar,
  Figma: Icons.Figma,
  "Final Cut Pro": Icons.FinalCutPro,
  Finder: Icons.Finder,
  "Firefox Developer Edition": Icons.FirefoxDeveloperEdition,
  Firefox: Icons.Firefox,
  "Firefox Nightly": Icons.FirefoxDeveloperEdition,
  Folx: Icons.Folx,
  GIMP: Icons.Gimp,
  "GitHub Desktop": Icons.GitHub,
  "GOG Galaxy": Icons.GogGalaxy,
  "Google Chrome Canary": Icons.GoogleChrome,
  "Google Chrome": Icons.GoogleChrome,
  "Grammarly Editor": Icons.Grammarly,
  GrandTotal: Icons.Dollar,
  HEY: Icons.Mail,
  Hyper: Icons.Terminal,
  Insomnia: Icons.Insomnia,
  "IntelliJ IDEA": Icons.Idea,
  Iris: Icons.Iris,
  Joplin: Icons.Joplin,
  Kakoune: Icons.Kakoune,
  KeePassXC: Icons.KeePassXC,
  "Keyboard Maestro": Icons.KeyboardMaestro,
  "Keychain Access": Icons.Key,
  Keynote: Icons.Keynote,
  "League of Legends": Icons.LeagueOfLegends,
  LibreWolf: Icons.LibreWolf,
  Linear: Icons.Linear,
  Live: Icons.Ableton,
  MAMP: Icons.Mamp,
  "MAMP PRO": Icons.Mamp,
  MacVim: Icons.Vim,
  Mail: Icons.Mail,
  MailMate: Icons.Mail,
  Mailspring: Icons.Mail,
  Matlab: Icons.Matlab,
  Mattermost: Icons.Mattermost,
  Messages: Icons.Messages,
  "Microsoft Edge": Icons.MicrosoftEdge,
  "Microsoft Excel": Icons.MicrosoftExcel,
  "Microsoft Outlook": Icons.MicrosoftOutlook,
  "Microsoft PowerPoint": Icons.MicrosoftPowerPoint,
  "Microsoft Teams": Icons.MicrosoftTeams,
  "Microsoft To Do": Icons.Things,
  "Microsoft Word": Icons.MicrosoftWord,
  Min: Icons.MinBrowser,
  MoneyMoney: Icons.Bank,
  Music: Icons.Music,
  Neovide: Icons.Vim,
  Notability: Icons.Notability,
  Notes: Icons.Notes,
  Notion: Icons.Notion,
  Nova: Icons.Nova,
  Numbers: Icons.Numbers,
  OBS: Icons.OBSStudio,
  Obsidian: Icons.Obsidian,
  OmniFocus: Icons.OmniFocus,
  Pages: Icons.Pages,
  "Parallels Desktop": Icons.Parallels,
  "Pi-hole Remote": Icons.Pihole,
  Pine: Icons.Pine,
  Podcasts: Icons.Podcasts,
  "PomoDone App": Icons.Pomodone,
  Preview: Icons.PDF,
  Receipts: Icons.Dollar,
  Reeder: Icons.Reeder5,
  Reminders: Icons.Reminders,
  Safari: Icons.Safari,
  "Safari Technology Preview": Icons.Safari,
  "Sequel Ace": Icons.SequelAce,
  "Sequel Pro": Icons.SequelPro,
  Setapp: Icons.Setapp,
  Signal: Icons.Signal,
  Sketch: Icons.Sketch,
  Skim: Icons.PDF,
  Skype: Icons.Skype,
  Slack: Icons.Slack,
  Spark: Icons.Spark,
  Spotify: Icons.Spotify,
  Spotlight: Icons.Spotlight,
	"Steam Helper": Icons.Steam,
  "Sublime Text": Icons.SublimeText,
  "System Preferences": Icons.Gear,
  "System Settings": Icons.Gear,
  TIDAL: Icons.Tidal,
  "TeamSpeak 3": Icons.TeamSpeak,
  Telegram: Icons.Telegram,
  Terminal: Icons.Terminal,
  "Text Edit": Icons.TextEdit,
  Things: Icons.Things,
  Thunderbird: Icons.Thunderbird,
  TickTick: Icons.TickTick,
  Todoist: Icons.Todoist,
  "Tor Browser": Icons.TorBrowser,
  Tower: Icons.Tower,
  Transmit: Icons.Transmit,
  Trello: Icons.Trello,
  Tweetbot: Icons.Twitter,
  Twitter: Icons.Twitter,
  Typora: Icons.Text,
  VLC: Icons.VLC,
  "VMware Fusion": Icons.VMwareFusion,
  VSCodium: Icons.VSCodium,
  Vim: Icons.Vim,
  VimR: Icons.Vim,
  Vivaldi: Icons.Vivaldi,
  WebStorm: Icons.WebStorm,
  WezTerm: Icons.Terminal,
  WhatsApp: Icons.WhatsApp,
  Xcode: Icons.Xcode,
  YouTube: Icons.YouTube,
  Zeplin: Icons.Zeplin,
  Zotero: Icons.Zotero,
  Zulip: Icons.Zulip,
  iTerm2: Icons.Terminal,
  kitty: Icons.Terminal,
  mpv: Icons.Mpv,
  qutebrowser: Icons.QuteBrowser,
  zathura: Icons.PDF,
  "zoom.us": Icons.Zoom,

  // German app names
  Nachrichten: Icons.Messages,

  // Chinese app names
  访达: Icons.Finder,
  邮件: Icons.Mail,
  微信: Icons.Wechat,
  网易云音乐: Icons.NeteaseMusic,
};
